[project]
name = "pomodog"
version = "0.1.0"
description = "Aplicativo Pomodoro com interface TUI de terminal integrada a ambiente Linux/GNU"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "textual>=8.2.8",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
